version: "2"
linters:
  default: standard
  # set of linters in addition to the default set (https://golangci-lint.run/usage/linters/#enabled-by-default)
  enable:
    - embeddedstructfieldcheck
    - gocritic
    - gosec
    - nilerr
    - revive
    - unconvert
    - unparam
    - whitespace
  exclusions:
    generated: lax
    rules:
      - linters:
        - revive
        path: (.+)defaults\.go$
        text: 'var-naming'
      - linters:
        - revive
        path: (.+)\.go$
        text: dot-imports # should not use dot imports
      - linters:
        - revive
        path: (.+)\.go$
        text: package-comments # package comment should be of the form
      - linters:
        - revive
        path: (.+)\.go$
        text: 'avoid meaningless package names'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
run:
  concurrency: 4
