apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: auditlog-forwarder
build:
  artifacts:
    - image: local-skaffold/auditlog-forwarder
      ko:
        dependencies:
          paths:
            - cmd/auditlog-forwarder
            - cmd/auditlog-forwarder/app
            - cmd/auditlog-forwarder/app/options
            - internal/backend
            - internal/backend/factory
            - internal/backend/http
            - internal/context
            - internal/handler/audit
            - internal/helper
            - internal/processor
            - internal/processor/annotation
            - pkg/apis/config/v1alpha1
            - pkg/apis/config/v1alpha1/validation
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/auditlog-forwarder
    - image: local-skaffold/echo-server
      ko:
        dependencies:
          paths:
            - cmd/echo-server
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/echo-server
  tagPolicy:
    customTemplate:
      template: '{{.version}}-{{.sha}}'
      components:
        - name: sha
          gitCommit:
            variant: AbbrevCommitSha
deploy:
  helm:
    releases:
      - name: echo-server
        chartPath: example/local-setup/charts/echo-server
        valuesFiles:
          - example/local-setup/charts/echo-server/values.yaml
        namespace: kube-system
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_local_skaffold_echo_server}}'
          image.tag: '{{.IMAGE_TAG_local_skaffold_echo_server}}@{{.IMAGE_DIGEST_local_skaffold_echo_server}}'
        setFiles:
          tls.crt: dev/local/certs/echo-server-tls.crt
          tls.key: dev/local/certs/echo-server-tls.key
          tls.clientCA: dev/local/certs/ca.crt
        createNamespace: false
        wait: true
      - name: auditlog-forwarder
        chartPath: example/local-setup/charts/auditlog-forwarder
        valuesFiles:
          - example/local-setup/charts/auditlog-forwarder/values.yaml
        namespace: kube-system
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_local_skaffold_auditlog_forwarder}}'
          image.tag: '{{.IMAGE_TAG_local_skaffold_auditlog_forwarder}}@{{.IMAGE_DIGEST_local_skaffold_auditlog_forwarder}}'
        setFiles:
          tls.crt: dev/local/certs/tls.crt
          tls.key: dev/local/certs/tls.key
          tls.clientCA: dev/local/certs/ca.crt
          backend.clientCrt: dev/local/certs/client.crt
          backend.clientKey: dev/local/certs/client.key
        createNamespace: false
        wait: true
