apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: auditlog-forwarder
build:
  artifacts:
    - image: local-skaffold/auditlog-forwarder
      ko:
        dependencies:
          paths:
            - cmd/auditlog-forwarder
            - cmd/auditlog-forwarder/app
            - cmd/auditlog-forwarder/app/options
            - internal/handler/audit
            - VERSION
        ldflags:
          - '{{.LD_FLAGS}}'
        main: ./cmd/auditlog-forwarder
  tagPolicy:
    customTemplate:
      template: '{{.version}}-{{.sha}}'
      components:
        - name: sha
          gitCommit:
            variant: AbbrevCommitSha
deploy:
  helm:
    releases:
      - name: auditlog-forwarder
        chartPath: example/local-setup/charts/auditlog-forwarder
        valuesFiles:
          - example/local-setup/charts/auditlog-forwarder/values.yaml
        namespace: kube-system
        setValueTemplates:
          image.repository: '{{.IMAGE_REPO_local_skaffold_auditlog_forwarder}}'
          image.tag: '{{.IMAGE_TAG_local_skaffold_auditlog_forwarder}}@{{.IMAGE_DIGEST_local_skaffold_auditlog_forwarder}}'
        setFiles:
          tls.crt: dev/local/certs/tls.crt
          tls.key: dev/local/certs/tls.key
        createNamespace: false
        wait: true
