---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditlog-forwarder
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: auditlog-forwarder
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auditlog-forwarder
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auditlog-forwarder
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: auditlog-forwarder
        image: {{ include "image" .Values.image }}
        imagePullPolicy: IfNotPresent
        args:
        - --port=10443
        - --tls-cert-file=/tls/tls.crt
        - --tls-private-key-file=/tls/tls.key
        ports:
        - name: port
          containerPort: 10443
          protocol: TCP
        volumeMounts:
        - name: tls
          mountPath: /tls
      volumes:
      - name: tls
        secret:
          secretName: auditlog-forwarder-tls
