apiVersion: v1
kind: Secret
metadata:
  name: auditlog-forwarder-tls
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
