---
apiVersion: v1
kind: Secret
metadata:
  name: auditlog-forwarder-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: auditlog-forwarder
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  ca.crt: {{ .Values.tls.clientCA | b64enc }}
