---
apiVersion: v1
kind: Secret
metadata:
  name: echo-server-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: echo-server
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  ca.crt: {{ .Values.tls.caCrt | b64enc | quote }}
