tls:
  crt: |
    -----BEGIN CERTIFICATE-----
    MIID...
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    MIIE...
    -----END PRIVATE KEY-----

image:
  repository: local-skaffold/echo-server
  tag: latest

config:
  port: 8443
  logBody: true
